package com.mehdisekoba.filimo.utils

enum class MoviesCategories(val item: Int) {
    SPECIAL(CATEGORY_SPECIAL),
    HOTTEST(CATEGORY_HOTTEST),
    ONLINE_SCREENING(CATEGORY_ONLINE_SCREENING),
    FILMO_EXCLUSIVE(CATEGORY_FILMO_EXCLUSIVE_SERIES),
    NEW_ONES(CATEGORY_THE_NEW_ONES),
    SPECIAL_OFFER(CATEGORY_THE_special),
    IRANIAN_SERIES(CATEGORY_IRANIAN_SERIES),
    ROMANTIC_SPECIAL(CATEGORY_ROMANTIC_SPECIAL)
}
